packages:
- '.'
resolver: lts-8.21
extra-deps:
- QuickCheck-2.10.0.1
- optparse-applicative-0.14.0.0
- criterion-1.2.1.0
- microstache-1
- statistics-0.14.0.2
- base-orphans-0.6
- path-0.6.1
- path-io-1.3.1
